# Generated by Django 5.1.5 on 2026-05-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('exam_type', models.CharField(default='NEET', max_length=50)),
                ('subjects', models.JSONField(default=list)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('total_marks', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=180)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generation_cost_paise', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='courses.course')),
            ],
            options={
                'db_table': 'pd_papers',
                'ordering': ['-created_at'],
            },
        ),
    ]
