# Generated by Django 5.1.5 on 2026-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittxn',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittxn',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittxn',
            name='ref',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
