# Generated by Django 5.1.5 on 2026-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_credittxn_input_tokens_credittxn_output_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('window_start', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pd_rate_limit_counters',
                'indexes': [models.Index(fields=['window_start'], name='pd_rate_lim_window__7a9ed8_idx')],
                'unique_together': {('key', 'window_start')},
            },
        ),
    ]
