# Generated by Django 5.1.5 on 2026-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_has_latex'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
