# Generated by Django 5.1.5 on 2026-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numeric_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='verification',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
