# Generated by Django 5.1.5 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_numeric_answer_question_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
