# Generated by Django 5.1.5 on 2026-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
