# Generated by Django 5.1.5 on 2026-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_pyq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
