# Generated by Django 5.1.5 on 2026-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_is_pyq_question_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calibrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='empirical_difficulty',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='empirical_p_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
