# Generated by Django 5.1.5 on 2026-07-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0006_generationjob'),
        ('users', '0003_backfill_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField()),
                ('options_per_question', models.IntegerField(default=4)),
                ('roll_digits', models.IntegerField(default=6)),
                ('layout', models.JSONField(default=dict)),
                ('sheet_version', models.IntegerField(default=1)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='omr/sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_sheets', to='users.organization')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_sheets', to='papers.paper')),
            ],
            options={
                'db_table': 'pd_omr_sheets',
                'ordering': ['-created_at'],
                'unique_together': {('paper', 'sheet_version')},
            },
        ),
        migrations.CreateModel(
            name='OMRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ok', max_length=20)),
                ('roll_number', models.CharField(blank=True, default='', max_length=20)),
                ('responses', models.JSONField(default=list)),
                ('needs_review', models.JSONField(default=list)),
                ('diagnostics', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_scans', to='users.organization')),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='omr.omrsheet')),
            ],
            options={
                'db_table': 'pd_omr_scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
