# Generated by Django 5.1.5 on 2026-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_add_org_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcourse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
