# Generated by Django 5.1.5 on 2026-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printtemplates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtemplate',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='footer_html',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='header_html',
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='style_config',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
