# Generated by Django 5.1.5 on 2026-06-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printtemplates', '0002_remove_printtemplate_custom_css_and_more'),
        ('users', '0003_backfill_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_templates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrintTemplateAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_template_audits', to='users.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pd_print_template_audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
