# Generated by Django 5.1.5 on 2026-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('NEET', 'NEET'), ('JEE Mains', 'JEE Mains'), ('JEE Advanced', 'JEE Advanced'), ('UPSC', 'UPSC'), ('Banking', 'Banking'), ('State PSC', 'State PSC')], default='NEET', max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pd_courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
