# Generated by Django 5.1.5 on 2026-05-19 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('exam', models.CharField(max_length=100)),
                ('total_q', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('scheduled_on', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
                ('enrolled', models.IntegerField(default=0)),
                ('attempted', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='courses.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pd_mock_tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
