# Generated by Django 5.1.5 on 2026-07-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Pinned to the earliest migration that creates each referenced table rather than to
    # whatever was latest when this was generated — those apps are under active development
    # and this app only needs the tables to exist, not their newest columns.
    dependencies = [
        ('mocktests', '0001_initial'),                 # MockTest
        ('papers', '0001_initial'),                    # Paper
        ('questions', '0001_initial'),                 # Question
        ('students', '0001_initial'),                  # Student
        ('users', '0002_add_organization'),            # Organization
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='in_progress', max_length=20)),
                ('total_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('online', 'Online'), ('omr', 'OMR'), ('manual', 'Manual')], default='online', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='mocktests.mocktest')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='users.organization')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='papers.paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.student')),
            ],
            options={
                'db_table': 'pd_student_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_snapshot_id', models.CharField(blank=True, default='', max_length=64)),
                ('selected_option_index', models.IntegerField(blank=True, null=True)),
                ('selected_option_indices', models.JSONField(blank=True, null=True)),
                ('numeric_answer', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unattempted', 'Unattempted'), ('correct', 'Correct'), ('partial', 'Partial'), ('incorrect', 'Incorrect')], default='unattempted', max_length=20)),
                ('marks_awarded', models.FloatField(default=0)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attempts.studentattempt')),
            ],
            options={
                'db_table': 'pd_question_responses',
            },
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['org', 'paper'], name='pd_attempt_org_paper_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['student'], name='pd_attempt_student_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['question'], name='pd_qresp_question_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
