# Generated by Django 5.1.5 on 2026-05-25 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_add_org_course_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('diagram_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=100)),
                ('schema', models.JSONField(help_text='Full diagram JSON schema (diagram_type, subtype, params, canvas)')),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_svg', models.TextField(blank=True, help_text='Pre-rendered SVG thumbnail', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pd_diagram_templates',
                'ordering': ['diagram_type', 'subtype'],
                'unique_together': {('diagram_type', 'subtype', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RenderedDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagram_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=100)),
                ('input_schema', models.JSONField(help_text='Full JSON input that was rendered')),
                ('svg_content', models.TextField(blank=True, help_text='Inline SVG string', null=True)),
                ('svg_path', models.CharField(blank=True, help_text='Relative path under MEDIA_ROOT', max_length=500, null=True)),
                ('png_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_result', models.JSONField(blank=True, null=True)),
                ('render_time_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, help_text='Source question this diagram belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_diagrams', to='questions.question')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_instances', to='diagrams.diagramtemplate')),
            ],
            options={
                'db_table': 'pd_rendered_diagrams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenderingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rendered_diagram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='diagrams.rendereddiagram')),
            ],
            options={
                'db_table': 'pd_rendering_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rendereddiagram',
            index=models.Index(fields=['diagram_type', 'subtype'], name='pd_rendered_diagram_d369e5_idx'),
        ),
        migrations.AddIndex(
            model_name='rendereddiagram',
            index=models.Index(fields=['status'], name='pd_rendered_status_11678d_idx'),
        ),
        migrations.AddIndex(
            model_name='rendereddiagram',
            index=models.Index(fields=['question'], name='pd_rendered_questio_9151ac_idx'),
        ),
    ]
