# Generated by Django 5.1.5 on 2026-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=100)),
                ('category', models.CharField(default='other', max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('sample_reason', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pd_diagram_demand',
                'ordering': ['-count'],
                'indexes': [models.Index(fields=['-count'], name='pd_diagram__count_0d5c16_idx')],
                'constraints': [models.UniqueConstraint(fields=('diagram_type', 'subtype', 'category'), name='uniq_diagram_demand_key')],
            },
        ),
    ]
